import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState, useRef } from "react";

import Gugudan from "../components/Gugudan";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>여러 가지 게임</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Gugudan />
    </>
  );
};

export default Home;
