import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState, useRef } from "react";

const Home: NextPage = () => {
  const [first, setFirst] = useState<number>(Math.ceil(Math.random() * 9));
  const [second, setSecond] = useState<number>(Math.ceil(Math.random() * 9));
  const [value, setValue] = useState<string>("");
  const [result, setResult] = useState<string>("");
  const inputRef = useRef<HTMLInputElement>(null);

  const onChangeInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setValue(value);
  };

  const onSubmitForm = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (parseInt(value) === first * second) {
      setResult(first + " x " + second + " = " + value + " 정답 ");
      setFirst(Math.ceil(Math.random() * 9));
      setSecond(Math.ceil(Math.random() * 9));
      setValue("");
    } else {
      setResult(first + " x " + second + " != " + value + " 오답 ");
      setValue("");
    }
    const inputAnswer = inputRef.current;
    inputAnswer?.focus();
  };

  return (
    <>
      <Head>
        <title>다른 글자 찾기</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        {first} 곱하기 {second} 는?
      </div>
      <form onSubmit={onSubmitForm}>
        <input ref={inputRef} onChange={onChangeInput} value={value} />
        <button>입력</button>
      </form>
      <div>{result}</div>
    </>
  );
};

export default Home;
